name: api_tests_stage
run-name: ⚙️ API tests STAGE

# will run on weekdays at 08:00 (Kiev TZ) / 03:00 EST
on:
  # schedule:
  #   - cron: '0 5 * * 1-5'
  push:
    branches:
      - main

# variables https://github.com/alexzavg/playwright_automation_showcase/settings/variables/actions
env:
  TZ:              ${{vars.TZ}}
  TEST_SUITE:      ${{vars.API_TESTS_STAGE}}
  SLACK_CHANNEL:   ${{vars.SLACK_CHANNEL}}
  SLACK_WEBHOOK:   ${{vars.SLACK_WEBHOOK}}
  SLACK_USER:      ${{vars.SLACK_USER}}
  CI_PIPELINE_URL: "https://github.com/ricardoveiga1/playwright_automation_practice/actions/runs/${{github.run_id}}"
  REPORT_URL:      ${{vars.HTML_REPORT_API_TESTS_STAGE}}
  NODE_VERSION:    20.x

jobs:
  api_tests:
    name: ⚙️ API tests STAGE
    runs-on: ubuntu-latest
    steps:
    - name: 🔎 List all environment variables
      run: env | sort

    - name: Checkout
      uses: actions/checkout@v4

    - name: 📗 Use node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 🔽 Install dependencies
      run: |
        npm install
        npm install -g ts-node
        npx playwright install chrome

    - name: 📝 Create .env file
      run: echo "${{secrets.CONFIG_STAGE}}" > .env.stage

    - name: ⚙️ Run API tests
      run: xvfb-run npm run $TEST_SUITE

    - name: 📊 Prepare HTML Report Directory
      if: always()
      run: |
        echo "Removing existing api_tests_stage directory if it exists..."
        rm -rf $GITHUB_WORKSPACE/api_tests_stage
        
        echo "Creating api_tests_stage directory..."
        mkdir -p $GITHUB_WORKSPACE/api_tests_stage
        
        echo "Current working directory:"
        pwd
        
        echo "Contents of the current working directory:"
        ls -la
        
        echo "Attempting to copy html-report to api_tests_stage directory"
        cp -r $GITHUB_WORKSPACE/html-report/* $GITHUB_WORKSPACE/api_tests_stage/
      shell: bash
    
    - name: 📊 Deploy HTML Report
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: api_tests_stage
        destination_dir: api_tests_stage

    - name: Notify Slack about success
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{\"channel\":\"$SLACK_CHANNEL\",\"username\":\"Playwright\",\"attachments\":[{\"color\":\"#2EB67D\",\"text\":\":test_tube: :white_check_mark: Test suite *$TEST_SUITE* has succeeded, :book: <$CI_PIPELINE_URL|VIEW LOGS>, :bar_chart: <$REPORT_URL|VIEW REPORT>\",\"footer\":\"Time: $(TZ=$TZ date)\"}]}" $SLACK_WEBHOOK
  
    - name: Notify Slack about failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{\"channel\":\"$SLACK_CHANNEL\",\"username\":\"Playwright\",\"attachments\":[{\"color\":\"#E01E5A\",\"text\":\":test_tube: :x: Test suite *$TEST_SUITE* has failed, :book: <$CI_PIPELINE_URL|VIEW LOGS>, :bar_chart: <$REPORT_URL|VIEW REPORT>, <$SLACK_USER>\",\"footer\":\"Time: $(TZ=$TZ date)\"}]}" $SLACK_WEBHOOK

    - name: Notify Slack about cancellation
      if: cancelled()
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{\"channel\":\"$SLACK_CHANNEL\",\"username\":\"Playwright\",\"attachments\":[{\"color\":\"#808080\",\"text\":\":test_tube: :black_square_for_stop: Test suite *$TEST_SUITE* was cancelled, :book: <$CI_PIPELINE_URL|VIEW LOGS>, :bar_chart: <$REPORT_URL|VIEW REPORT>, <$SLACK_USER>\",\"footer\":\"Time: $(TZ=$TZ date)\"}]}" $SLACK_WEBHOOK
  